# Generated by Django 3.1.7 on 2021-04-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bus_no', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=600)),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.bus')),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
    ]
