# Generated by Django 3.1.7 on 2021-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20210401_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
