# Generated by Django 3.1.7 on 2021-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20210401_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_no',
            field=models.TextField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='description',
            field=models.TextField(),
        ),
    ]
