# Generated by Django 3.2 on 2021-04-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_auto_20210414_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('j_type', models.BooleanField(default=1)),
                ('date', models.TextField()),
                ('start', models.TextField(default=0)),
                ('end', models.TextField(default=0)),
                ('gps', models.TextField()),
                ('last_update', models.TextField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.bus')),
            ],
        ),
    ]
