# Generated by Django 3.2 on 2021-04-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active_ride_j_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='driver.journey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='expires',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='token',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='journey',
            table='Journey',
        ),
    ]
