# Generated by Django 3.2 on 2021-04-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
    ]
