# Generated by Django 3.1.7 on 2021-03-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('section', models.CharField(max_length=64)),
                ('photo', models.FileField(upload_to='')),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.bus')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
            ],
            options={
                'db_table': 'Kid',
            },
        ),
    ]
